### ISSUE TITLE
schematic file doesn't open in eagle

### ISSUE THREAD

**Issue by yogee1707** [satshas/satshakit#1] opened 2016-05-15 20:05 UTC
This year I'm doing FAB Academy 2016. For my input devices assignment. 
I'm using the Ubuntu 16.04 and I've using EAGLE 7.5.0 to open the .sch or .brd file. EAGLE shown. 

while opening files with EAGLE I got the error as follows 

**Loading /home/yogee/eagle/satshaKit/satshakit_cnc.brd ...

Error:

line 6, column 41: This is not an EAGLE file.**

and

**
Loading /home/yogee/eagle/satshaKit/satshakit_cnc.sch ...

Error:

line 6, column 41: This is not an EAGLE file.
**

Wondering why this is happening. Because as per my knowledge the all EAGLE files are backward compatible.

**Comment by satshas** [comment] 2016-05-15 21:35
Hello,
I have done the following:
1. tried to open all the Eagle files in the repo using Ubuntu 16.04 x64 (fresh virtual box install) with Eagle 7.5.0, and is possible to **open all of them with no problems**
2. tried to open again all the files using Mac OSX with Eagle 7.5.0, **everything ok**
3. tried to open again all the files using Windows 10 with Eagle 7.5.0, **everything ok**

Maybe the issue is elsewhere?
How do you downloaded the files?
Could you try to do so using in terminal -> git clone https://github.com/satshas/satshakit.git

Let me know if you solve the problem.

Thanks.

Daniele.

**Comment by satshas** [comment] 2016-05-17 08:14
Ok, the problem is actually that you downloaded directly the sch/brd form the link of the repo. There you have to right click and download as. Otherwise you get something changed by the browser.

I have updated the repo with this instruction in each download section, therefore I am closing this issue. 

Please open another one if you still have problems.

**Closed as completed by satshas** 2016-05-17 08:14 UTC

**Comment by yogee1707** [comment] 2016-05-21 10:35
Have cloned the repo and able to open file without any problem. Thank You.
